server:
  port: 8081

# Kafka Producer 設定
spring:
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:host.docker.internal:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

# gRPC 設定
grpc:
  client:
    inventory-service:
      # 本機測試時連 localhost:9090；上 K8s 時這行會自動被 DNS 覆蓋或手動改為 static://inventory-service:9090
      # 本機連本機
      # address: 'static://localhost:9090'  
      # 本機連k8s 
      # address: 'static://localhost:30090'  
      # 加上 dns:/// 讓 gRPC 使用 K8s 的內建域名解析
      address: 'dns:///inventory-service:9090'
      negotiationType: PLAINTEXT